import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import "../styles/globals.css";
import { Header } from "@/widgets/Header";
import { Footer } from "@/widgets/Footer";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;  
};

export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale} className={nunito.variable} data-theme="cupcake">
      <body>
        <NextIntlClientProvider>
          <div id="main">
            <Header />
            <main id="main-block">{children}</main>
            <Footer />
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
