import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { hasLocale, NextIntlClientProvider } from "next-intl";

import { Header } from "@/widgets/Header";
import { Footer } from "@/widgets/Footer";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import NextTopLoader from "nextjs-toploader";

import "../styles/globals.css";
import { ContactProvider } from "../provider/ContactProvider";
import { getContact } from "@/shared/lib/api/get-contact";
import { NetworkStatus } from "@/shared/ui/NetworkStatus";
import { Toaster } from "react-hot-toast";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;
  const contactResponse = await getContact();

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale} className={nunito.variable} data-theme="cupcake">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
        />
      </head>
      <body>
        <NextTopLoader
          color="#2be5eb"
          height={4}
          shadow="0 0 10px #11b2b8, 0 0 5px #031b1c"
        />
        <NextIntlClientProvider>
          <NetworkStatus />
          <ContactProvider data={contactResponse.data.data}>
            <div id="main">
              <Header />
              <main id="main-block">{children}</main>
              <Footer />
            </div>

            <Toaster />
          </ContactProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
